### ISSUE TITLE
Refactor Printout() function of view.go

### ISSUE THREAD

**Issue by grafvonb** [NTTDATA-DACH/viewnode#12]
The current version is too complicated and too long. Refactoring required.

**Comment by trkelly23** [comment]
Hi Adam, I agree the PrintOut method could use some refactoring and simplification.  I'd like to work on it if you don't mind.  Would you be open to using TabWriter to better format the output?

**Comment by grafvonb** [comment]
@trkelly23 Yes, a better output would be great. However, since we already have some users, please provide a CLI switch so that users can use the "old style" output if they wish.

**Comment by trkelly23** [comment]
Thanks for the feedback.  I can keep the prior output and help with the transition from old to new with a switch.  I ready to start working but ran into a permission error.  Can you grant my user access to the repo?
remote: Permission to NTTDATA-DACH/viewnode.git denied to trkelly23.
fatal: unable to access 'https://github.com/NTTDATA-DACH/viewnode.git/': The requested URL returned error: 403

**Comment by grafvonb** [comment]
Hi, it is a "normal process", just make a fork of the project, create and work on a feature branch and after you are done with the issue, create a pull request to the main branch. Thanks :).

**Comment by grafvonb** [comment]
Replaced by https://github.com/NTTDATA-DACH/viewnode/issues/16
