### ISSUE TITLE
provide arm64 darwin

### ISSUE THREAD

**Issue by zhilyaev** [NTTDATA-DACH/viewnode#22]
```
failed to install plugin "viewnode": plugin "viewnode" does not offer installation for this platform
failed to install some plugins: [viewnode]: plugin "viewnode" does not offer installation for this platform
```

**Comment by grafvonb** [comment]
@zhilyaev Hi, the PR https://github.com/kubernetes-sigs/krew-index/pull/2752 is waiting now for the final approval. After that you should be able to install and check if `viewnode` arm64/darwin version works as expected. Please let me know about it. Thanks!

**Comment by zhilyaev** [comment]
@grafvonb  thanks a lot!
